name: CI

on:
  push:
    branches: ["main", "devel"]
    paths:
      - '**.go'
      - '**.yml'
  pull_request:
    branches: ["main"]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v7

      - name: Set up Go
        uses: actions/setup-go@v6
        with:
          go-version: 'stable'
          cache: true

      - name: Run Tests with Coverage
        run: go test -v -coverprofile=profile.cov ./...

      - name: Run Tests with Unsafe Tag
        run: go test -tags=unsafe -v ./...

      - name: Send Coverage to Goveralls
        uses: shogo82148/actions-goveralls@v1
        with:
          path-to-profile: profile.cov

  linting:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v7

      - name: Set up Go
        uses: actions/setup-go@v6
        with:
          go-version: 'stable'

      - name: golangci-lint without build tag
        uses: golangci/golangci-lint-action@v9
        with:
          version: latest

      - name: golangci-lint with unsafe build tag
        uses: golangci/golangci-lint-action@v9
        with:
          version: latest
          args: --build-tags=unsafe
